"""add positive

Revision ID: b0f4a1059c77
Revises: c677bd1b0e6d
Create Date: 2018-01-16 18:34:33.017162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f4a1059c77'
down_revision = 'c677bd1b0e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('positive', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'positive')
    # ### end Alembic commands ###
