"""add followers

Revision ID: c677bd1b0e6d
Revises: 31028fd4d1fd
Create Date: 2018-01-16 10:47:09.170588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c677bd1b0e6d'
down_revision = '31028fd4d1fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('follow_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'follow_num')
    # ### end Alembic commands ###
